mongodb:
    connectionstring: "mongodb+srv://prakashsr:rqEICMCTPE5y0P4M@fiscluster.ulxri.mongodb.net/LendingAcc?authSource=admin&replicaSet=atlas-147hh6-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true"
    genericForms: "mongodb+srv://prakashsr:rqEICMCTPE5y0P4M@fiscluster.ulxri.mongodb.net/generic-forms-accelerator?retryWrites=true&w=majority"
    ssncollectionname: "SSNDetails"
    creditscorecollectionname: "CreditScoreDetails"
    plaidUserCredsCol: "UserCredentials"
    formData: "forms-data"
    customerformdata: "customer-onboarding-form-data"
http:
  port: "8081" 

microbilt:
  ssnrequesthost: "apitest.microbilt.com" 
  ssnaddressrequestpath: "/SSNAddressVerification"
  ssnnamerequestpath: "/SSNNameVerification" 
  ssnphonerequestpath: "/SSNPhoneVerification"    
  ssnrequestpath: "/SSNValidation/GetReport"    
  ssnrequesturl: "https://apitest.microbilt.com/SSNAddressVerification/"
  client_id : "vGf5GSfLoILxAMLYF1QR51AsIJdGvJG4"
  client_secret : "LAG6YHHPb0RwH7Ci"
  token_url : "https://apitest.microbilt.com/OAuth/GetAccessToken"

expirySeconds: "172800"

api:
  autodiscovery: "18539741"
      
sfdc:
  COAutoVerification: "COAutoVerification"
  user: "dineshdini075@wise-hawk-jkfgkz.com"
  password: "Classmate@1234"
  secToken: "2VX3OTpqzLLRpPoeJHtCn9QD"
  aggReq: "customeronboarding-salesforce-api.sg-s1.cloudhub.io"
  loanApplicant: "/customer/customerdetails"
  getStatus: "/customer/customerdetailsbyemail"
#http://customeronboarding-salesforce-api.sg-s1.cloudhub.io/api/customer/customerdetails
plaid:
  accessToken: "access-sandbox-590e3bc6-ab0b-4d74-9248-fac1164e89d7"
  getIdentity: "sandbox.plaid.com"
  
email:
  commsAcc: "nous-comms-accelerator.sg-s1.cloudhub.io"
  sendMail: "/comms/notify/email"
  
  
otp:
  host: "multi-factor-authentication-api.sg-s1.cloudhub.io"
  generate: "/generate-otp-send"
  verify: "/verify-otp"
  
